import { createFileRoute } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { z } from "zod";
import { SceneRenderer } from "@/components/SceneRenderer";

const search = z.object({ q: z.string().optional() });

export const Route = createFileRoute("/create")({
  component: Create,
  validateSearch: search,
  head: () => ({
    meta: [
      { title: "Studio — MathViz" },
      { name: "description", content: "Type a prompt and generate an animated math explainer." },
    ],
  }),
});

function buildScript(prompt: string) {
  const safe = prompt.replace(/[^a-zA-Z0-9 ]/g, " ").trim() || "Visualize an idea";
  const className = safe.split(/\s+/).slice(0, 3).map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join("") + "Scene";
  return `from manim import *

class ${className}(Scene):
    """Auto-generated by MathViz.
    Prompt: ${safe}
    """
    def construct(self):
        title = Text("${safe}", font_size=42)
        self.play(Write(title))
        self.wait(0.6)
        self.play(title.animate.to_edge(UP))

        axes = Axes(
            x_range=[-4, 4, 1], y_range=[-2, 2, 1],
            axis_config={"include_tip": True},
        )
        graph = axes.plot(lambda x: np.sin(x), color=BLUE)
        label = MathTex("y = \\\\sin(x)").next_to(graph, UR)

        self.play(Create(axes), run_time=1.2)
        self.play(Create(graph), Write(label))
        self.wait(2)
`;
}

function Create() {
  const { q } = Route.useSearch();
  const [prompt, setPrompt] = useState(q ?? "");
  const [status, setStatus] = useState<"idle" | "thinking" | "rendering" | "done">("idle");
  const [script, setScript] = useState("");

  useEffect(() => { if (q) setPrompt(q); }, [q]);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!prompt.trim()) return;
    setStatus("thinking");
    setScript("");
    await new Promise((r) => setTimeout(r, 900));
    setScript(buildScript(prompt));
    setStatus("rendering");
    await new Promise((r) => setTimeout(r, 1400));
    setStatus("done");
  }

  return (
    <div className="mx-auto max-w-6xl px-6 py-12">
      <div className="mb-8">
        <p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Studio</p>
        <h1 className="mt-2 font-display text-4xl md:text-5xl">Compose a scene</h1>
        <p className="mt-2 max-w-xl text-muted-foreground">
          Describe what you want to visualize. MathViz drafts a script and previews the animation.
        </p>
      </div>

      <form onSubmit={handleGenerate} className="rounded-2xl border border-border/70 bg-card/60 p-5 shadow-[var(--shadow-glow)]">
        <div className="flex items-start gap-3">
          <span className="mt-3 font-mono text-xs text-muted-foreground">PROMPT</span>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g. Animate the proof of the Pythagorean theorem"
            rows={3}
            className="flex-1 resize-none bg-transparent text-lg outline-none placeholder:text-muted-foreground/60"
          />
        </div>
        <div className="mt-4 flex items-center justify-between">
          <span className="text-xs text-muted-foreground">Tip: be specific about objects, colors, and timing.</span>
          <button
            type="submit"
            disabled={status === "thinking" || status === "rendering"}
            className="rounded-full bg-primary px-5 py-2 text-sm font-medium text-primary-foreground transition hover:opacity-90 disabled:opacity-60"
          >
            {status === "thinking" ? "Drafting…" : status === "rendering" ? "Rendering…" : "Generate"}
          </button>
        </div>
      </form>

      <div className="mt-10 grid gap-6 md:grid-cols-2">
        <div className="rounded-2xl border border-border/70 bg-card/40 p-5">
          <div className="mb-3 flex items-center justify-between">
            <h2 className="font-display text-lg">Preview</h2>
            <span className="font-mono text-xs text-muted-foreground">
              {status === "idle" && "ready"}
              {status === "thinking" && "drafting script…"}
              {status === "rendering" && "rendering frames…"}
              {status === "done" && "complete"}
            </span>
          </div>
          {status === "done" ? (
            <SceneRenderer prompt={prompt} />
          ) : (
            <div className="grid h-[360px] place-items-center rounded-3xl border border-dashed border-border/70 bg-background/30 text-center">
              <div>
                <div className="mx-auto mb-3 h-10 w-10 rounded-full border-2 border-primary/40 border-t-primary animate-spin" style={{ opacity: status === "idle" ? 0.2 : 1 }} />
                <p className="text-sm text-muted-foreground">
                  {status === "idle" ? "Your animation will appear here." : "Working on your scene…"}
                </p>
              </div>
            </div>
          )}
        </div>

        <div className="rounded-2xl border border-border/70 bg-card/40 p-5">
          <div className="mb-3 flex items-center justify-between">
            <h2 className="font-display text-lg">Generated script</h2>
            {script && (
              <button
                onClick={() => navigator.clipboard.writeText(script)}
                className="rounded-full border border-border bg-background/40 px-3 py-1 text-xs hover:border-primary/40"
              >
                Copy
              </button>
            )}
          </div>
          <pre className="max-h-[360px] overflow-auto rounded-xl border border-border/60 bg-background/60 p-4 text-xs leading-relaxed text-foreground/90">
{script || "# Your script will appear here.\n# Try: 'Visualize the unit circle and sine wave together'"}
          </pre>
        </div>
      </div>
    </div>
  );
}
